Add `Keys` sync message
whisperfish/libsignal-service-rs pull request #310
Opened 2024-07-14 18:42 UTC by direc85

Take two, intentionally (for development convenience) branched of an old commit - the one Whisperfish `main` currently uses.

Untested, but should work.

I tried to remove passing self-recipient, but couldn't figure out a way to get it in the method. I think that would require setting self service address to sender, which would break API, so I'm not delving into that currently.

2024-09-08 21:11 UTC, direc85 commented
Added WIP for MasterKey and StorageServiceKey, as well as MasterKeyStorage, which is probably done in some funky manner. Improvements and corrections welcome...

2024-09-09 20:15 UTC, gferon commented
Thanks! At the risk of missing the point, why was this suddenly needed? :smile:

2024-09-10 04:29 UTC, direc85 commented
These are needed to properly support the Keys sync message, which is needed for linking nowadays... Ruben suggested making these into a trait, I'm not at all sure I did that in a good way.

Basically this part should be quite ready, but there's still the "where are these actually used" side of things...

2024-09-29 22:38 UTC, direc85 commented
We still must test this code, but review-wise this PR can be considered ready.

2024-10-03 13:53 UTC, rubdos requested changes
Some generalizations, otherwise looking clean to me! :-)

2024-10-03 13:53 UTC, rubdos commented on libsignal-service/src/master_key.rs
> +        slice: &Vec<u8>,
```suggestion
        slice: &[u8],
```

2024-10-03 13:53 UTC, rubdos commented on libsignal-service/src/master_key.rs
> +        slice: &Vec<u8>,
```suggestion
        slice: &[u8],
```

2024-10-03 15:54 UTC, rubdos approved these changes

2024-10-03 15:54 UTC, merged