chore: fix clippy 1.81
whisperfish/libsignal-service-rs pull request #323
Opened 2024-09-20 15:51 UTC by boxdot

2024-09-20 20:56 UTC, rubdos requested changes
Thanks :-)

2024-09-20 20:56 UTC, rubdos commented on libsignal-service/examples/storage.rs
> +
Can you annotate the section where this is needed, instead of a global allow? If not, can you write a comment why this is here?

2024-09-20 20:56 UTC, rubdos commented on libsignal-service/src/messagepipe.rs
> +#[allow(clippy::diverging_sub_expression)]
Here too, a comment explaining why it triggers, and why we suppress would be nice.

2024-09-30 06:44 UTC, rubdos commented
@boxdot kind ping for the requested changes; maybe it wasn't clear from the notification that it was a change request :'-)

2024-09-30 08:03 UTC, boxdot commented
> @boxdot kind ping for the requested changes; maybe it wasn't clear from the notification that it was a change request :'-)

Thank you for reminding me. I got carried away.

2024-09-30 08:43 UTC, rubdos commented
Lint reasons don't seem to be stabilized yet in 1.75, any chance we can put the reason behind a nightly flag? Sounds a bit wrong to bump MSRV for this :'-)

(Sailfish is on 1.75 still, and will be for at least half a year I fear)

2024-09-30 09:04 UTC, rubdos approved these changes

2024-09-30 09:04 UTC, merged